Repository team-xquare/v1-service-application, pull requests merged in 2022-10, with the labels that each got.

#160 🔀 :: (#159) 자습실 신청 일자 버그
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
Labels: 버그

#163 🔀 :: (#162) OpenFeign 설정
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-infrastructure/build.gradle
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/FeignClientErrorDecoder.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/FeignConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/error/FeignBadRequestException.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/error/FeignExpiredTokenException.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/error/FeignForbiddenException.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/error/FeignUnAuthorizedException.java
Labels: 프로젝트 설정

#164 🔀 :: (#161) 자습실 학생 리스트 기능 제작
  application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryQueryStudyRoomRepository.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/service/StudyRoomApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/spi/QueryStudyRoomRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/spi/StudyRoomQueryExtensionRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/spi/StudyRoomUserFeignSpi.java
  application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/repository/CustomExtensionRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/UserClient.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/UserClientImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/dto/response/UserInfoResponse.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/dto/response/UserInfoResponseElement.java
  application-infrastructure/src/main/resources/application.yml
Labels: 기능 추가

#168 🔀 :: (#167) 잔류 버그
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/exception/AlreadyExistsStayException.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
Labels: 버그

#166 🔀 :: (#165) cloud config 설정
  .github/CODEOWNERS
  .github/workflows/prod-build.yaml
  .github/workflows/stg-build.yml
  Dockerfile
  application-infrastructure/build.gradle
  application-infrastructure/src/main/resources/application.yml
Labels: 리팩토링, 기능 추가

#172 🔀 :: (#171) 자습실 신청 상태 조회 Api OSIV 영향
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
Labels: 버그

#170 🔀 :: (#169) 자습실 신청 취소 Api
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/api/StudyRoomApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/exception/ExtensionNotFoundException.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/exception/InCorrectStudyRoomIdException.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/service/StudyRoomApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/spi/StudyRoomPostExtensionRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/spi/StudyRoomQueryExtensionRepositorySpi.java
  application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/repository/CustomExtensionRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/mapper/ExtensionMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java
Labels: 기능 추가

#174 🔀 :: (#173) 자습실 신청 취소 Api
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/service/StudyRoomApiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/mapper/ExtensionMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/mapper/ExtensionMapperImpl.java
Labels: 버그

#176 🔀 :: (#175) CORS credentials
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/WebConfig.java
Labels: 기능 추가
