Repository team-xquare/v1-service-application, pull requests merged in 2022-05, with the labels that each got.

#9 🔀 :: (#8) CI 수정
  .github/workflows/ci-lint.yml
Labels: chore

#7 🔀 :: (#6) Migration to Hexagonal Architecture
  application-domain/build.gradle
  application-domain/src/main/java/io/github/v1serviceapplication/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/annotation/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/extensionapply/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/picnicapply/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/stayapply/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmealapply/.gitkeep
  application-infrastructure/build.gradle
  application-infrastructure/src/main/java/io/github/v1serviceapplication/V1ServiceApplicationApplication.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extensionapply/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicapply/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stayapply/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealapply/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/.gitkeep
  build.gradle
  settings.gradle
  src/main/java/com/v1/applicationservice/ApplicationServiceApplication.java
  src/main/java/com/v1/applicationservice/domain/stayapply/service/.gitkeep
  src/main/java/com/v1/applicationservice/domain/studyroom/domain/.gitkeep
  src/main/java/com/v1/applicationservice/domain/studyroom/exception/.gitkeep
  src/main/java/com/v1/applicationservice/domain/studyroom/presentation/.gitkeep
  src/main/java/com/v1/applicationservice/domain/studyroom/service/.gitkeep
  src/main/java/com/v1/applicationservice/domain/weekendmealapply/domain/.gitkeep
  src/main/java/com/v1/applicationservice/domain/weekendmealapply/exception/.gitkeep
  src/main/java/com/v1/applicationservice/domain/weekendmealapply/presentation/.gitkeep
  src/main/java/com/v1/applicationservice/domain/weekendmealapply/service/.gitkeep
  src/main/resources/application.properties
Labels: 리팩토링

#11 🔀 :: (#10) domain model 작성
  application-domain/build.gradle
  application-domain/src/main/java/io/github/v1serviceapplication/annotation/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/annotation/Aggregate.java
  application-domain/src/main/java/io/github/v1serviceapplication/annotation/DomainService.java
  application-domain/src/main/java/io/github/v1serviceapplication/annotation/Spi.java
  application-domain/src/main/java/io/github/v1serviceapplication/extensionapply/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/extensionapply/ExtensionApply.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnicapply/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/picnicapply/PicnicApply.java
  application-domain/src/main/java/io/github/v1serviceapplication/stayapply/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/stayapply/StayApply.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/StudyRoom.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmealapply/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmealapply/WeekendMealApply.java
  build.gradle
Labels: 기능 추가

#12 🔀 :: (#4) entity 작성
  application-infrastructure/build.gradle
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extensionapply/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extensionapply/ExtensionApply.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicapply/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicapply/PicnicApply.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stayapply/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stayapply/StayApply.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/StudyRoom.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealapply/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealapply/WeekendMealApply.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseUUIDEntity.java
  application-infrastructure/src/main/resources/application.yml
Labels: 기능 추가

#14 🔀 :: (#13) querydsl 세팅
  application-infrastructure/build.gradle
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/config/QuerydslConfig.java
Labels: 기능 추가

#16 🔀 :: (#15) CODEOWNERS 추가
  .github/CODEOWNERS
Labels: 기능 추가

#21 🔀 :: (#20) dependency 수정
  application-infrastructure/build.gradle
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/config/FilterConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/handler/ExceptionHandlerFilter.java
Labels: chore

#30 🔀 :: (#29) 아키텍처 리팩토링
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extensionapply/domain/ExtensionApply.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicapply/domain/PicnicApply.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stayapply/domain/StayApply.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/StudyRoom.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealapply/domain/WeekendMealApply.java
Labels: 리팩토링

#23 🔀 :: (#22) ExceptionHandler 작성
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/handler/GlobalExceptionHandler.java
Labels: 기능 추가

#32 🔀 :: (#31) repository 추가
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extensionapply/domain/ExtensionApplyEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extensionapply/domain/repository/ExtensionApplyRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicapply/domain/PicnicApplyEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicapply/domain/repository/PicnicApplyRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stayapply/domain/StayApplyEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stayapply/domain/repository/StayApplyRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/StudyRoomEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/StudyRoomRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealapply/domain/WeekendMealApplyEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealapply/domain/repository/WeekendMealApplyRepository.java
Labels: 기능 추가

#34 🔀 :: (#33) Entity Renaming
  application-domain/src/main/java/io/github/v1serviceapplication/.gitkeep
  application-domain/src/main/java/io/github/v1serviceapplication/extension/Extension.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/Picnic.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/Stay.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/WeekendMeal.java
  application-infrastructure/build.gradle
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/.gitkeep
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extension/domain/ExtensionEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extension/domain/repository/ExtensionRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extensionapply/domain/repository/ExtensionApplyRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicapply/domain/repository/PicnicApplyRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/StayConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/mapper/StayMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stayapply/domain/repository/StayApplyRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/StudyRoomEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/WeekendMealRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealapply/domain/repository/WeekendMealApplyRepository.java
Labels: 리팩토링

#38 🔀 :: (#37) CODEOWNERS
  .github/CODEOWNERS
Labels: 프로젝트 설정
