Repository team-xquare/v1-service-application, pull requests merged in 2022-09, with the labels that each got.

#140 🔀 :: (#135) 퍼사드 의존성 리팩토링
  application-domain/src/main/java/io/github/v1serviceapplication/common/UserIdFacade.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/dto/ApplyWeekendPicnicDomainRequest.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/StayApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/api/StudyRoomApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/service/StudyRoomApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/WeekendMealApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java
  application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/SetDefaultStayRequest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/WeekendMealController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/facade/UserIdFacadeImpl.java
Labels: 리팩토링

#144 🔀 :: (#142) Stay 리팩토링 오류
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/ApplyStay.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/QueryStayStatus.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/QueryStayStatusCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/SetDefaultStay.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayCodeController.java
Labels: 리팩토링, 버그

#147 🔀 :: swagger 설정
  application-infrastructure/build.gradle
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayCodeController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/WeekendMealController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/config/SwaggerConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
  application-infrastructure/src/main/resources/application.yml
Labels: 기능 추가

#151 🔀 :: (#150) 잔류 신청 API 응답코드 수정
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
Labels: 리팩토링

#155 🔀 :: (#149) 회원가입 실패 시 보상 트랜잭션 호출 API 작성
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/StayApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
Labels: chore, 기능 추가

#154 ♻️ :: 로직 수정
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/StayApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/SignupSettingRequest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
Labels: chore
