Repository team-xquare/v1-service-application, pull requests merged in 2022-06, with the labels that each got.

#40 🔀 :: (#35) 테스트 환경 구축
  application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java
  application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java
  build.gradle
Labels: 프로젝트 설정, 테스트 추가

#43 🔀 :: (#42) 자습실 목록 버그
  application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/spi/dto/StudyRoomModel.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extension/domain/ExtensionEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/vo/StudyRoomVO.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseUUIDEntity.java
Labels: 버그

#45 🔀 :: (#26) 자습실 신청 API
  application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/StudyRoom.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/extension/Extension.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/api/PostStudyRoom.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/service/PostStudyRoomImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/spi/PostStudyRoomRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImpl.java
  application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/StudyRoomEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/ExtensionEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/repository/ExtensionRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/mapper/StudyRoomMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/dto/request/PostStudyRoomRequest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseUUIDEntity.java
Labels: 기능 추가

#51 🔀 :: (#50) 자습실 목록 Api 반환값 수정
  application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/api/dto/response/StudyRoomElement.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/spi/dto/StudyRoomModel.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/vo/StudyRoomVO.java
Labels: 기능 추가

#52 🔀 :: (#49) 신청 Entity 수정
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/Picnic.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/Stay.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/StudyRoom.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/extension/Extension.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/WeekendMeal.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/ExtensionEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseEntity.java
Labels: 기능 추가

#48 🔀 :: (#44) Error 핸들링
  application-domain/src/main/java/io/github/v1serviceapplication/error/ApplicationException.java
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/exception/AlreadyJoinStudyRoomException.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/exception/FullStudyRoomException.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/service/PostStudyRoomImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorAttribute.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorHandlingFilter.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorResponse.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/GlobalErrorCode.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/AttributeConvertFailedException.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/BadRequestException.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/GlobalException.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/NotFoundException.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/UnexpectedException.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/handler/ErrorResponse.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/handler/GlobalExceptionHandler.java
Labels: 기능 추가, 프로젝트 설정

#56 🔀 :: (#24) 잔류 신청 API
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/ApplyStay.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/ApplyStayImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/code/StayStatusCode.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/mapper/StayMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/ApplyStayRequest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/ConvertFailedException.java
Labels: 기능 추가

#61 🔀 :: (#60) build.gradle jar option
  build.gradle
Labels: chore, 프로젝트 설정

#62 🔀 :: (#60) build.gradle jar option
  Dockerfile
  application-infrastructure/build.gradle
Labels: chore, 프로젝트 설정

#63 🔀 :: (#60) build.gradle jar option
  Dockerfile
Labels: 프로젝트 설정

#66 🔀 :: (#59) base Entity 리팩토링
  application-infrastructure/src/main/java/io/github/v1serviceapplication/V1ServiceApplicationApplication.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseEntity.java
Labels: 리팩토링

#65 🔀 :: (#64) ErrorHandlingFilter 등록
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorHandlingFilter.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
Labels: chore, 기능 추가

#71 🔀 :: (#70) security 설정 추가
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
Labels: chore

#73 🔀 :: (#72) code converter 리팩토링
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/ApplyStay.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/code/StayStatusCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/ApplyStayImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/code/StayStatusCode.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/converter/StayStatusCodeConverter.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/ApplyStayRequest.java
Labels: 리팩토링

#76 🔀 :: (#57) 잔류 상태 조회 API
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/error/StayNotFoundException.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/QueryStayStatus.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/dto/response/QueryStayStatusResponse.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/QueryStayStatusImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
Labels: 기능 추가

#78 🔀 :: (#27) 주말 외출 신청 API
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/ApplyWeekendPicnic.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/dto/ApplyWeekendPicnicDomainRequest.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/ApplyWeekendPicnicImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/spi/PicnicRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/PicnicConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/mapper/PicnicMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/dto/request/ApplyWeekendPicnicRequest.java
Labels: 기능 추가

#77 🔀 :: (#25) 주말 급식 신청 API
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/api/PostWeekendMeal.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/service/PostWeekendMealImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/spi/PostWeekendMealRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/WeekendMealConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/WeekendMealController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/dto/request/PostWeekendMealRequest.java
Labels: 기능 추가

#80 🔀 :: (#79) test code
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
Labels: 리팩토링

#82 🔀 :: (#25) 주말 급식 신청 API
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/WeekendMealConfig.java
Labels: 기능 추가

#83 🔀 :: (#81) jwtParser 삭제, 모든 api permitAll
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/jwt/JwtParser.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/jwt/TokenFilter.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/property/JwtProperty.java
  application-infrastructure/src/main/resources/application.yml
Labels: chore

#85 🔀 :: (#84) cd 파일 수정
  .github/workflows/prod-build.yaml
  .github/workflows/stg-build.yml
Labels: 리팩토링

#87 🔀 :: (#86) UUID 통일
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
Labels: 프로젝트 설정

#91 🔀 :: (#90) Exception Handling
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorHandlingFilter.java
Labels: 버그

#93 🔀 :: (#92) 자습실 신청 Api 중복처리 변경
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/exception/AlreadyJoinStudyRoomException.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/service/PostStudyRoomImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/spi/PostStudyRoomRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/exception/ExtensionNotFoundException.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/exception/StudyRoomNotFoundException.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/ExtensionEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/repository/ExtensionRepository.java
Labels: 기능 추가

#99 🔀 :: (#98) queryStayStatus 이번 주 값으로
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
Labels: 버그

#101 🔀 :: (#100) 사소한 버그
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
Labels: chore, 버그

#103 🔀 :: (#102) 자습실 신청 상태 조회 Api
  application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/api/QueryStudyRoomStatus.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomStatusImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/spi/StudyRoomRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/dto/response/StudyRoomStatusResponse.java
Labels: 기능 추가

#107 🔀 :: (#106) 주말 급식 테이블 작성
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/WeekendMealApply.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/api/PostWeekendMealApply.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/service/PostWeekendMealApplyImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/spi/PostWeekendMealApplyRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/spi/PostWeekendMealRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/ExtensionEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/WeekendMealConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealApplyEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealApplyRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/WeekendMealApplyRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/WeekendMealRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealApplyMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/WeekendMealController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/dto/request/PostWeekendMealApplyRequest.java
Labels: 기능 추가

#105 🔀 :: (#104) config authorization/authentication
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/role/UserRole.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/AuthenticationFilter.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
Labels: 기능 추가

#110 🔀 :: (#109) 주말급식 조회 Api 작성
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/WeekendMeal.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/WeekendMealApply.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/exception/WeekendMealNotFoundException.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/api/PostWeekendMealApply.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/service/PostWeekendMealApplyImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/spi/PostWeekendMealApplyRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/api/QueryWeekendMeal.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/service/QueryWeekendMealImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/spi/QueryWeekendMealRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealApplyEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealApplyRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealApplyMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealApplyMapperImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/WeekendMealController.java
Labels: 기능 추가

#113 🔀 :: (#111) 주말급식 신청 Api 수정
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/ApplyWeekendPicnicImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/service/PostStudyRoomImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/spi/PostStudyRoomRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/exception/WeekendMealApplyNotFoundException.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/service/PostWeekendMealApplyImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/spi/PostWeekendMealApplyRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealApplyEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealApplyRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/WeekendMealApplyRepository.java
Labels: 기능 추가

#115 🔀 :: (#108) filter config
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/AuthenticationFilter.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
Labels: chore

#116 🔀 :: (#75) 주말급식 신청 상태 조회
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/service/PostWeekendMealApplyImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/spi/PostWeekendMealApplyRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/api/QueryWeekendMeal.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/api/dto/QueryWeekendMealResponse.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/service/QueryWeekendMealImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/spi/QueryWeekendMealApplyRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealApplyEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealApplyRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/WeekendMealApplyRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealApplyMapperImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/WeekendMealController.java
Labels: 기능 추가

#117 🔀 :: (#114) 유저 인증 리팩토링
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/role/UserRole.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/AuthenticationFilter.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
Labels: 리팩토링

#121 🔀 :: (#119) authentication filter refactoring
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/AuthenticationFilter.java
Labels: chore

#120 🔀 :: (#118) 유저 회원가입
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/SetDefaultStay.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/SetDefaultStayImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/SetDefaultStayRequest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
Labels: 기능 추가
