Repository team-xquare/v1-service-application, pull requests merged in 2022-07, with the labels that each got.

#123 🔀 :: (#122) 자습실 목록 Api 수정
  application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/StudyRoom.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/api/QueryStudyRoom.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/spi/StudyRoomRepositorySpi.java
  application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/StudyRoomEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorHandlingFilter.java
Labels: 기능 추가

#125 🔀 :: (#122) 자습실 목록 Api 수정
  application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/StudyRoom.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/api/QueryStudyRoom.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/spi/StudyRoomRepositorySpi.java
  application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/StudyRoomEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorHandlingFilter.java
Labels: 기능 추가

#126 🔀 :: (#124) Actions ECR 이전
  .github/workflows/prod-build.yaml
  .github/workflows/stg-build.yml
Labels: 프로젝트 설정

#129 🔀 :: (#128) userId 받아오는 로직 수정, 라우터 권한 설정
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/dto/ApplyWeekendPicnicDomainRequest.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/ApplyWeekendPicnicImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/api/QueryStayStatus.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/QueryStayStatusImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/api/PostStudyRoom.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/service/PostStudyRoomImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/api/QueryStudyRoomStatus.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomStatusImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/api/PostWeekendMealApply.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/service/PostWeekendMealApplyImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/api/QueryWeekendMeal.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/service/QueryWeekendMealImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/WeekendMealController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
Labels: chore
