Repository team-xquare/v1-service-application, pull requests merged in 2023-05, with the labels that each got.

#205 🔀 :: (#12) 주말 외출 신청 삭제 API
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/PicnicApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/spi/PicnicRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java
Labels: 기능 추가

#198 🔀 :: (#197) HTTP line is larger than 4096 bytes 에러 방지 코드 변경
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/spi/PicnicUserFeignSpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayUserFeignSpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/studyroom/service/StudyRoomApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/user/UserIdFacade.java
  application-domain/src/main/java/io/github/v1serviceapplication/user/dto/response/UserInfoElement.java
  application-domain/src/main/java/io/github/v1serviceapplication/user/spi/UserFeignSpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/spi/WeekendMealUserFeignSpi.java
  application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/facade/UserIdFacadeImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/dto/request/UserInfoRequest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/user/UserClient.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/user/UserClientImpl.java
Labels: 버그

#208 🔀 :: (#47) Jpa 쿼리명 버그 수정
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/repository/ExtensionRepository.java
Labels: chore, 버그

#210 🔀 :: (#24) 주말 외출 가능 시간 조회 API
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/PicnicApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/dto/PicnicAllowTimeResponse.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnicdatetime/spi/PicnicTimeRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicdatetime/domain/repository/PicnicTimeRepositorySpiImpl.java
Labels: 기능 추가

#209 🔀 :: (#23) Exception 코드 추가
  application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java
Labels: chore

#206 🔀 :: (#13) 주말 외출증 수정 API
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/error/PicnicPassModifyForbiddenException.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/PicnicApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/dto/UpdatePicnicDomainRequest.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/spi/PicnicRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/dto/request/UpdatePicnicRequest.java
Labels: 기능 추가

#212 🔀 :: (#39) 시간 조회 코드 수정
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/Picnic.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/PicnicApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/dto/PicnicAllowTimeResponse.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/dto/PicnicElement.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/spi/PicnicRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnicdatetime/DayType.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnicdatetime/PicnicTime.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnicdatetime/TimeType.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnicdatetime/spi/PicnicTimeRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/mapper/PicnicMapperImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/AdminPicnicController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicdatetime/domain/PicnicTimeEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicdatetime/domain/mapper/PicnicTimeMapperImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicdatetime/domain/repository/PicnicTimeRepositorySpiImpl.java
Labels: chore, 리팩토링

#213 🔀 :: (#89) 주말 외출 가능한 시간 조회 조건문 수정
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicdatetime/domain/repository/PicnicTimeRepositorySpiImpl.java
Labels: chore, 리팩토링

#215 🔀 :: (#38) 주말 외출 엑셀 다운로드 컬럼값 수정
  application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/presentation/PicnicReservationController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
  application-infrastructure/src/main/resources/application.yml
Labels: 리팩토링, 프로젝트 설정

#217 🔀 :: (#42) 외출 복귀 기능 삭제
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/Picnic.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/PicnicApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/spi/PicnicRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/mapper/PicnicMapperImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/AdminPicnicController.java
Labels: chore

#218 🔀 :: (#44) 주말 외출 리스트 엑셀 API 수정
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
Labels: chore

#219 🔀 :: (#49) 주말 외출 가능한 시간 조회 코드 수정
  application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
Labels: chore, 버그

#220 🔀 :: (#106) 주말 외출 조회 where문 조건에 들어가는 메소드 수정
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
Labels: chore, 버그
