Repository team-xquare/v1-service-application, pull requests merged in 2023-06, with the labels that each got.

#222 🔀 :: (#44) 주말급식 선생님 확인 API
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/WeekendMealCheck.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/exception/WeekendMealCheckNotFoundException.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/spi/PostWeekendMealCheckRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/spi/QueryWeekendMealCheckRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/WeekendMealApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/AdminWeekendMealController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/dto/PostWeekendMealCheckRequest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/WeekendMealCheckEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/repository/CustomWeekendMealCheckRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/repository/WeekendMealCheckRepository.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/mapper/WeekendMealCheckMapper.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/mapper/WeekendMealCheckMapperImpl.java
Labels: 기능 추가

#216 🔀 :: (#40) CODEOWNERS 추가
  .github/CODEOWNERS
Labels: chore

#223 🔀 :: (#131) Sentry 세팅
  application-infrastructure/build.gradle
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorHandlingFilter.java
  application-infrastructure/src/main/resources/application.yml
Labels: chore

#225 🔀 :: (#125) 주말 급식 리스트 API 수정
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/spi/QueryWeekendMealCheckRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/dto/WeekendMealListResponse.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/spi/QueryWeekendMealApplyRepositorySpi.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/repository/CustomWeekendMealCheckRepositoryImpl.java
Labels: chore, 버그

#227 🔀 :: (#137) 주말급식 학생 신청 상태 변경 API
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/WeekendMealApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/AdminWeekendMealController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/dto/request/ChangeStudentWeekendMealApplyStatusRequest.java
Labels: 기능 추가

#211 🔀 :: (#1) sqs Request
  application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java
  application-domain/src/main/java/io/github/v1serviceapplication/error/JsonConvertException.java
  application-domain/src/main/java/io/github/v1serviceapplication/notification/NotificationSpi.java
  application-infrastructure/build.gradle
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/notification/NotificationAdapter.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/notification/dto/DomainSendGroupMessageRequest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/notification/dto/DomainSendMessageRequest.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/config/AmazonSqsConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/config/SchedulerConfig.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/notification/scheduler/NotificationScheduler.java
Labels: 기능 추가

#228 🔀 :: (#140) 주말급식 엑셀 API 수정
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/AdminWeekendMealController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendMealAllStudentExcel.java
Labels: chore, 버그

#229 🔀 :: (#143) 주말외출 알람 Cron 시간 변경
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/notification/scheduler/NotificationScheduler.java
Labels: chore

#230 🔀 :: (#149) 주말급식 신청 API 수정 및 주말급식 담임 선생님 확인 API로 분리
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/WeekendMealCheck.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/spi/QueryWeekendMealCheckRepositorySpi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/WeekendMealApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/dto/WeekendMealCheckStatusResponse.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/dto/WeekendMealListResponse.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/AdminWeekendMealController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/WeekendMealCheckEntity.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/repository/CustomWeekendMealCheckRepositoryImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/mapper/WeekendMealCheckMapperImpl.java
Labels: chore

#233 🔀 :: (#160) 허용 도메인 추가
  application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/WebConfig.java
Labels: 버그

#234 🔀 :: (#170) 주말급식 허용 기간 조회 API
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/WeekendMealApi.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/dto/WeekendMealAllowedPeriodResponse.java
  application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/AdminWeekendMealController.java
  application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/notification/scheduler/NotificationScheduler.java
Labels: chore, 기능 추가
